import 'dart:async';
import 'package:flutter/foundation.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

/// FirebaseService — wraps Firestore write operations for the OpenAamps app.
///
/// Uses the official FlutterFire SDK (cloud_firestore). Credentials are
/// configured automatically via firebase_options.dart (generated by flutterfire).
class FirebaseService extends ChangeNotifier {
  static final FirebaseService instance = FirebaseService._internal();
  FirebaseService._internal();

  FirebaseFirestore? get _firestore {
    try {
      return FirebaseFirestore.instance;
    } catch (_) {
      return null;
    }
  }

  FirebaseAuth? get _auth {
    try {
      return FirebaseAuth.instance;
    } catch (_) {
      return null;
    }
  }

  bool _isConnected = false;
  DateTime? _lastSyncTime;
  String _statusMessage = 'Ready';

  bool get isConnected => _isConnected;
  DateTime? get lastSyncTime => _lastSyncTime;
  String get statusMessage => _statusMessage;

  // For compatibility with code that checks these:
  bool get isConfigured => true; // Configured via firebase_options.dart
  String get projectId {
    try {
      return _firestore?.app.options.projectId ?? 'openaamps';
    } catch (_) {
      return 'openaamps';
    }
  }

  String get apiKey {
    try {
      return _firestore?.app.options.apiKey ?? 'AIzaSyBEky_XxWxdJ26FHZAUzScaPMGuD4bs3U0';
    } catch (_) {
      return 'AIzaSyBEky_XxWxdJ26FHZAUzScaPMGuD4bs3U0';
    }
  }

  /// Initialize — wires up auth state listener to track connection status.
  Future<void> initialize() async {
    try {
      final auth = _auth;
      if (auth == null) return;
      auth.authStateChanges().listen((user) {
        if (user != null) {
          _isConnected = true;
          _statusMessage = 'Connected as ${user.email ?? user.uid}';
        } else {
          _isConnected = false;
          _statusMessage = 'Not signed in';
        }
        notifyListeners();
      });
    } catch (e) {
      debugPrint('[FirebaseService] Auth listener init skipped: $e');
    }
  }

  /// Write or merge a document in Firestore.
  Future<bool> syncDocumentToFirestore({
    required String collection,
    required String documentId,
    required Map<String, dynamic> fields,
  }) async {
    final auth = _auth;
    final firestore = _firestore;
    if (auth == null || firestore == null) {
      return false;
    }

    final user = auth.currentUser;
    if (user == null) {
      debugPrint('[FirebaseService] Skipping Firestore sync — user not signed in');
      return false;
    }

    try {
      await firestore
          .collection(collection)
          .doc(documentId)
          .set(fields, SetOptions(merge: true));

      _lastSyncTime = DateTime.now();
      _isConnected = true;
      _statusMessage = 'Last synced ${_lastSyncTime!.toLocal()}';
      notifyListeners();
      return true;
    } catch (e) {
      debugPrint('[FirebaseService] Firestore write error: $e');
      _isConnected = false;
      _statusMessage = 'Sync failed: $e';
      notifyListeners();
      return false;
    }
  }

  /// Sync acoustic listening preferences for the signed-in user.
  Future<bool> syncAcousticPreferences(Map<String, dynamic> prefs) async {
    final auth = _auth;
    final uid = auth?.currentUser?.uid;
    if (uid == null) return false;

    return syncDocumentToFirestore(
      collection: 'user_preferences',
      documentId: uid,
      fields: {
        ...prefs,
        'updatedAt': FieldValue.serverTimestamp(),
      },
    );
  }

  /// Read acoustic preferences for the signed-in user.
  Future<Map<String, dynamic>?> loadAcousticPreferences() async {
    final auth = _auth;
    final firestore = _firestore;
    if (auth == null || firestore == null) return null;

    final uid = auth.currentUser?.uid;
    if (uid == null) return null;

    try {
      final doc = await firestore
          .collection('user_preferences')
          .doc(uid)
          .get();
      return doc.exists ? doc.data() : null;
    } catch (e) {
      debugPrint('[FirebaseService] Firestore read error: $e');
      return null;
    }
  }

  /// Save a play event to the user's listening history.
  Future<void> recordPlayEvent({
    required String trackId,
    required String title,
    required String artist,
    double listenedSeconds = 0,
  }) async {
    final auth = _auth;
    final firestore = _firestore;
    if (auth == null || firestore == null) return;

    final uid = auth.currentUser?.uid;
    if (uid == null) return;

    try {
      await firestore
          .collection('listening_history')
          .doc(uid)
          .collection('events')
          .add({
        'trackId': trackId,
        'title': title,
        'artist': artist,
        'listenedSeconds': listenedSeconds,
        'playedAt': FieldValue.serverTimestamp(),
      });
    } catch (e) {
      debugPrint('[FirebaseService] History write error: $e');
    }
  }
}
